If patching fails, abort git am session.  Added improved error checking.
Signed-off-by: Steve Dunnagan <sdunnaga@redhat.com>

diff --git a/kbuild_centos b/kbuild_centos
--- a/kbuild_centos
+++ b/kbuild_centos
@@ -41,7 +41,7 @@ CLEAN=false
 CONFIGURE=false
 GIT_CLONE=false
 CROSS_COMPILE_PREFIX=""
-KERNEL_ID="chopin"
+CUSTOM_KERNEL_ID="chopin"
 BUILD_SUCCESS=false
 PATCHES_DIR=""
 
@@ -50,8 +50,9 @@ RED=$(tput setaf 1)
 GREEN=$(tput setaf 2)
 YELLOW=$(tput setaf 3)
 LIME_YELLOW=$(tput setaf 190)
-POWDER_BLUE=$(tput setaf 153)
 BLUE=$(tput setaf 4)
+BRIGHT_BLUE=$(tput setaf 12)
+POWDER_BLUE=$(tput setaf 153)
 MAGENTA=$(tput setaf 5)
 CYAN=$(tput setaf 6)
 WHITE=$(tput setaf 7)
@@ -66,9 +67,9 @@ usage() {
     echo "Usage: $0" \
          "[-a x86_64|aarch64|riscv64]" \
          "[-g (git clone)]" \
-         "[-f (configure)]" \
+         "[-f (configure kernel)]" \
          "[-c (clean)]" \
-         "[-b (backporting)]" \
+         "[-b (prepare for backporting)]" \
          "[-p <patches_dir> (specify patches directory)]"
     exit 1
 }
@@ -93,10 +94,15 @@ if [[ -z "$KERNEL_SRC_DIR" || -z "$KERNEL_BUILD_DIR" ]]; then
     echo "${NORMAL}"
     exit 1
 else
-    echo "${WHITE}KERNEL_SRC_DIR =   ${POWDER_BLUE}${BOLD}${KERNEL_SRC_DIR}${NORMAL}"
-    echo "${WHITE}KERNEL_BUILD_DIR = ${POWDER_BLUE}${BOLD}${KERNEL_BUILD_DIR}"
+    echo "${WHITE}KERNEL_SRC_DIR =   ${BRIGHT_BLUE}${BOLD}${KERNEL_SRC_DIR}${NORMAL}"
+    echo "${WHITE}KERNEL_BUILD_DIR = ${BRIGHT_BLUE}${BOLD}${KERNEL_BUILD_DIR}"
     echo "${NORMAL}"
 fi
+
+command -v git >/dev/null 2>&1 || { echo "git is required but not installed. Exiting."; exit 1; }
+command -v make >/dev/null 2>&1 || { echo "make is required but not installed. Exiting."; exit 1; }
+command -v ctags >/dev/null 2>&1 || { echo "ctags is required but not installed. Exiting."; exit 1; }
+command -v cpupower >/dev/null 2>&1 || { echo "cpupower is required but not installed. Exiting."; exit 1; }
 
 # Set the target architecture and cross-compilation prefix based on the
 # specified target architecture and the current system's architecture.
@@ -128,7 +134,8 @@ case "$TARGET_ARCH" in
         CROSS_COMPILE_PREFIX=""
         ;;
     *)
-        echo "Unsupported target architecture: $TARGET_ARCH"
+        echo "${RED}${BOLD}Invalid architecture specified: $TARGET_ARCH. Supported: aarch64, riscv64, x86_64."
+        echo "${NORMAL}"
         exit 1
         ;;
 esac
@@ -137,17 +144,18 @@ esac
 if [[ "$CLEAN" == true ]]; then
     echo "${WHITE}Cleaning the build..."
     echo "${NORMAL}"
-    if [[ -n "$KERNEL_BUILD_DIR" ]]; then
-        #make O=$KERNEL_BUILD_DIR clean
-        rm -rf "${KERNEL_BUILD_DIR}"
-    else
-        make clean
-    fi
+    rm -rf "${KERNEL_BUILD_DIR}"
 fi
 
-# Create the kernel build dir if it doesn't exist yet.
-if [ ! -d "$KERNEL_BUILD_DIR" ]; then
+# Ensure KERNEL_BUILD_DIR exists
+if [[ ! -d "$KERNEL_BUILD_DIR" ]]; then
     mkdir -p "$KERNEL_BUILD_DIR"
+fi
+
+# Ensure KERNEL_BUILD_DIR is writable
+if [[ ! -w "$KERNEL_BUILD_DIR" ]]; then
+    echo "Error: KERNEL_BUILD_DIR is not writable: $KERNEL_BUILD_DIR"
+    exit 1
 fi
 
 # Clone the CS9 kernel source repository.
@@ -156,11 +164,12 @@ if [[ "$GIT_CLONE" == true ]]; then
     if [ -d "$KERNEL_SRC_DIR" ]; then
         echo "${YELLOW}${BOLD}"
         echo "WARNING: The kernel source directory ($KERNEL_SRC_DIR) exists."
-        read -p "Are you sure you want to remove the existing workspace? This action is irreversible. Type 'yes' to confirm: ${NORMAL}" confirmation
+        read -p "Are you sure you want to remove the existing workspace? Type 'yes' to confirm: ${NORMAL}" confirmation
+        confirmation=${confirmation:-no} # Default to 'no'
         echo "${NORMAL}"
         if [[ "$confirmation" == "yes" ]]; then
-            echo "${WHITE}Removing ${POWDER_BLUE}${BOLD}$KERNEL_SRC_DIR${NORMAL}..."
-            echo "${WHITE}Removing ${POWDER_BLUE}${BOLD}$KERNEL_BUILD_DIR..."
+            echo "${WHITE}Removing ${BRIGHT_BLUE}${BOLD}$KERNEL_SRC_DIR${NORMAL}..."
+            echo "${WHITE}Removing ${BRIGHT_BLUE}${BOLD}$KERNEL_BUILD_DIR..."
             echo "${NORMAL}"
             rm -rf "$KERNEL_SRC_DIR"
             rm -rf "$KERNEL_BUILD_DIR"
@@ -182,6 +191,7 @@ if [[ "$GIT_CLONE" == true ]]; then
     cd "$KERNEL_SRC_DIR" || exit 1
 
     # Build ctags
+    echo ""
     echo "${WHITE}Generating ctags ..."
     echo "${NORMAL}"
     export TMPDIR=~/tmp
@@ -198,7 +208,7 @@ if [[ "$GIT_CLONE" == true ]]; then
     fi
 
     # Set a build identifier.
-    sed -i "s/^\(EXTRAVERSION\s*=\s*\)\(.*\)/\1\2 -$KERNEL_ID/" Makefile
+    sed -i "s/^\(EXTRAVERSION\s*=\s*\)\(.*\)/\1\2 -$CUSTOM_KERNEL_ID/" Makefile
 
     # Create build directory if specified.
     if [[ -n "$KERNEL_BUILD_DIR" ]]; then
@@ -217,26 +227,30 @@ else
 fi
 
 # Apply patches
+shopt -s nullglob  # Ensure empty glob doesn't break the loop
 if [ -n "$PATCHES_DIR" ] && [[ -d "$PATCHES_DIR" ]]; then
     echo ""
-    echo "${WHITE}Applying patches from ${POWDER_BLUE}${BOLD}$PATCHES_DIR..."
+    echo "${WHITE}Applying patches from ${BRIGHT_BLUE}${BOLD}$PATCHES_DIR..."
     echo "${NORMAL}"
+    
+    patches_found=false
 
-    # Loop through each patch file in the directory
     for patch_file in "$PATCHES_DIR"/*.patch; do
         if [[ -f "$patch_file" ]]; then
-            echo "${POWDER_BLUE}${BOLD}$patch_file${NORMAL}"
+            patches_found=true
+            echo "${CYAN}$patch_file${NORMAL}"
             git am "$patch_file" || {
-                echo "${RED}${BOLD}Error: Failed to apply patch ${POWDER_BLUE}${BOLD}$patch_file${NORMAL}"
-                exit 1
+                echo "${RED}${BOLD}Error: Failed to apply patch ${BRIGHT_BLUE}${BOLD}$patch_file${NORMAL}";
+                git am --abort;
+                exit 1;
             }
-        else
-            echo "${RED}${BOLD}"
-            echo "Error: No patches found in $PATCHES_DIR"
-            echo "${NORMAL}"
-            exit 1
         fi
     done
+
+    if ! $patches_found; then
+        echo "${RED}${BOLD}Error: No patches found in $PATCHES_DIR${NORMAL}"
+        exit 1
+    fi
 fi
 
 # Configure the CS9 kernel.
@@ -251,7 +265,7 @@ if $CONFIGURE; then
     # Copy a CS9 kernel config to use as a starting point.
     cp "${CONFIG_FILE}" "${KERNEL_BUILD_DIR:-.}/.config"
     echo ""
-    echo "${WHITE}CentOS Stream 9 kernel config: ${POWDER_BLUE}${BOLD}${CONFIG_FILE}"
+    echo "${WHITE}CentOS Stream 9 kernel config: ${BRIGHT_BLUE}${BOLD}${CONFIG_FILE}"
     echo "${NORMAL}"
 
     # Perform mrproper if using a separate build directory.
@@ -262,32 +276,25 @@ if $CONFIGURE; then
     # Validate and automatically update the CS9 kernel config.
     if [[ -n "$KERNEL_BUILD_DIR" ]]; then
         make ARCH="$MAKE_ARCH" O="$KERNEL_BUILD_DIR" olddefconfig
-    else
-        make ARCH="$MAKE_ARCH" olddefconfig
     fi
 
     # Run menuconfig so user can customize the kernel config.
     echo ""
-    echo "${WHITE}Do you want to run menuconfig? (y/n)${NORMAL}"
+    echo "${WHITE}Do you want to run menuconfig? (yes/no)${NORMAL}"
     read -r answer
-    if [[ "$answer" =~ ^[Yy]$ ]]; then
+    answer="${answer:-no}"  # Default to "no" if no input is provided
+    if [[ "$answer" =~ ^[Yy](es)?$ ]]; then
         if [[ -n "$CROSS_COMPILE_PREFIX" ]]; then
             # Cross-compile
             if [[ -n "$KERNEL_BUILD_DIR" ]]; then
-                # Separate build dir.
                 make ARCH="$MAKE_ARCH" CROSS_COMPILE="${CROSS_COMPILE_PREFIX}" O="$KERNEL_BUILD_DIR" menuconfig
-            else
-                make ARCH="$MAKE_ARCH" CROSS_COMPILE="${CROSS_COMPILE_PREFIX}" menuconfig
             fi
         else
             # Native build
             if [[ -n "$KERNEL_BUILD_DIR" ]]; then
-                # Separate build dir.
                 make ARCH="$MAKE_ARCH" O="$KERNEL_BUILD_DIR" menuconfig
-            else
-                make ARCH="$MAKE_ARCH" menuconfig
             fi
-        fi
+        fi  
     else
         echo "${WHITE}Skipping menuconfig.${NORMAL}"
     fi
@@ -342,7 +349,10 @@ else
         ARCH=\"$MAKE_ARCH\""
 fi
 
-echo "Build command: ${MAKE_CMD}" | tee -a "$LOG_FILE"
+echo ""
+echo "${WHITE}Build command: ${BRIGHT_BLUE}${BOLD}${MAKE_CMD}"
+echo "${NORMAL}"
+echo "Build command: ${MAKE_CMD}" >> "$LOG_FILE"
 echo "" >> "$LOG_FILE"
 eval "$MAKE_CMD" 2>&1 | tee -a "$LOG_FILE"
 
