Fixed unbounded variable error.
Signed-off-by: Steve Dunnagan <sdunnaga@redhat.com>

diff --git a/kbuild_centos b/kbuild_centos
--- a/kbuild_centos
+++ b/kbuild_centos
@@ -43,6 +43,7 @@ GIT_CLONE=false
 CROSS_COMPILE_PREFIX=""
 KERNEL_ID="chopin"
 BUILD_SUCCESS=false
+PATCHES_DIR=""
 
 BLACK=$(tput setaf 0)
 RED=$(tput setaf 1)
@@ -92,10 +93,8 @@ if [[ -z "$KERNEL_SRC_DIR" || -z "$KERNEL_BUILD_DIR" ]]; then
     echo "${NORMAL}"
     exit 1
 else
-    echo "${WHITE}"
-    echo "KERNEL_SRC_DIR =   ${POWDER_BLUE}${BOLD}${KERNEL_SRC_DIR}"
-    echo "${NORMAL}${WHITE}"
-    echo "KERNEL_BUILD_DIR = ${POWDER_BLUE}${BOLD}${KERNEL_BUILD_DIR}"
+    echo "${WHITE}KERNEL_SRC_DIR =   ${POWDER_BLUE}${BOLD}${KERNEL_SRC_DIR}${NORMAL}"
+    echo "${WHITE}KERNEL_BUILD_DIR = ${POWDER_BLUE}${BOLD}${KERNEL_BUILD_DIR}"
     echo "${NORMAL}"
 fi
 
@@ -136,12 +135,11 @@ esac
 
 # Clean the build.
 if [[ "$CLEAN" == true ]]; then
-    echo "${WHITE}"
-    echo "Cleaning the build..."
+    echo "${WHITE}Cleaning the build..."
     echo "${NORMAL}"
     if [[ -n "$KERNEL_BUILD_DIR" ]]; then
         #make O=$KERNEL_BUILD_DIR clean
-        rm -rf $KERNEL_BUILD_DIR
+        rm -rf "${KERNEL_BUILD_DIR}"
     else
         make clean
     fi
@@ -162,13 +160,12 @@ if [[ "$GIT_CLONE" == true ]]; then
         echo "${NORMAL}"
         if [[ "$confirmation" == "yes" ]]; then
             echo "${WHITE}Removing ${POWDER_BLUE}${BOLD}$KERNEL_SRC_DIR${NORMAL}..."
-            echo "${WHITE}Removing ${POWDER_BLUE}${BOLD}$KERNEL_BUILD_DIR${NORMAL}..."
+            echo "${WHITE}Removing ${POWDER_BLUE}${BOLD}$KERNEL_BUILD_DIR..."
+            echo "${NORMAL}"
             rm -rf "$KERNEL_SRC_DIR"
             rm -rf "$KERNEL_BUILD_DIR"
-            echo ""
         else
-            echo "${WHITE}"
-            echo "Workspace was not removed. Please reconsider your life choices."
+            echo "${WHITE}Workspace was not removed. Please reconsider your life choices."
             echo "${NORMAL}"
             exit 1
         fi
@@ -176,14 +173,29 @@ if [[ "$GIT_CLONE" == true ]]; then
 
     # Clone the CS9 kernel source.
     if [[ ! -d "$KERNEL_SRC_DIR" ]]; then
-        echo "${WHITE}"
-        echo "Cloning the CS9 kernel source tree..."
+        echo "${WHITE}Cloning the CS9 kernel source tree..."
         echo "${NORMAL}"
         git clone https://gitlab.com/$USER/centos-stream-9 "$KERNEL_SRC_DIR"
     fi
 
     # Change dir to the newly cloned kernel source.
     cd "$KERNEL_SRC_DIR" || exit 1
+
+    # Build ctags
+    echo "${WHITE}Generating ctags ..."
+    echo "${NORMAL}"
+    export TMPDIR=~/tmp
+    mkdir -p "$TMPDIR"
+    ctags --append=yes --sort=yes --recurse --links=no --languages=C,C++,Python \
+          --c-kinds=+p --fields=+iaS --extras=+q \
+          --exclude="*.o" --exclude="*.so" --exclude="*.a" --exclude="*.bin" \
+          --exclude=".git/*"
+    if [ "$?" -ne 0 ]; then
+        echo "${RED}${BOLD}"
+        echo "Error: Failed to generate tags" >&2
+        echo "${NORMAL}"
+        exit 1
+    fi
 
     # Set a build identifier.
     sed -i "s/^\(EXTRAVERSION\s*=\s*\)\(.*\)/\1\2 -$KERNEL_ID/" Makefile
@@ -205,10 +217,10 @@ else
 fi
 
 # Apply patches
-if [[ -d "$PATCHES_DIR" ]]; then
+if [ -n "$PATCHES_DIR" ] && [[ -d "$PATCHES_DIR" ]]; then
     echo ""
-    echo "${WHITE}Applying patches from ${POWDER_BLUE}${BOLD}$PATCHES_DIR${NORMAL}..."
-    echo ""
+    echo "${WHITE}Applying patches from ${POWDER_BLUE}${BOLD}$PATCHES_DIR..."
+    echo "${NORMAL}"
 
     # Loop through each patch file in the directory
     for patch_file in "$PATCHES_DIR"/*.patch; do
@@ -227,80 +239,63 @@ if [[ -d "$PATCHES_DIR" ]]; then
     done
 fi
 
-# Build ctags
-echo "${WHITE}"
-echo "Generating ctags ..."
-echo "${NORMAL}"
-ctags --append=yes --sort=yes --recurse --links=no --languages=C,C++,Python \
-      --c-kinds=+p --fields=+iaS --extras=+q \
-      --exclude="*.o" --exclude="*.so" --exclude="*.a" --exclude="*.bin" \
-      --exclude=".git/*"
-if [ "$?" -ne 0 ]; then
-    echo "${RED}${BOLD}"
-    echo "Error: Failed to generate tags" >&2
-    echo "${NORMAL}"
-    exit 1
-fi
-
 # Configure the CS9 kernel.
 if $CONFIGURE; then
     # Generate all CS9 kernel configs.
-    echo "${WHITE}"
-    echo "Generating all CS9 kernel configs..."
+    echo ""
+    echo "${WHITE}Generating CS9 kernel configs..."
     echo "${NORMAL}"
     make dist-configs
     CONFIG_FILE="redhat/configs/kernel-5.14.0-${TARGET_ARCH}-debug.config"
 
     # Copy a CS9 kernel config to use as a starting point.
     cp "${CONFIG_FILE}" "${KERNEL_BUILD_DIR:-.}/.config"
-    echo "${WHITE}"
-    echo "CentOS Stream 9 kernel config ${POWDER_BLUE}${BOLD}${CONFIG_FILE}"
+    echo ""
+    echo "${WHITE}CentOS Stream 9 kernel config: ${POWDER_BLUE}${BOLD}${CONFIG_FILE}"
     echo "${NORMAL}"
 
     # Perform mrproper if using a separate build directory.
     if [[ -n "$KERNEL_BUILD_DIR" ]]; then
         make ARCH="$MAKE_ARCH" mrproper
-        echo "${WHITE}"
-        echo "Running make ARCH=$MAKE_ARCH mrproper..."
-        echo "${NORMAL}"
     fi
 
     # Validate and automatically update the CS9 kernel config.
-    echo "${WHITE}"
-    echo "Running olddefconfig..."
-    echo "${NORMAL}"
     if [[ -n "$KERNEL_BUILD_DIR" ]]; then
         make ARCH="$MAKE_ARCH" O="$KERNEL_BUILD_DIR" olddefconfig
     else
         make ARCH="$MAKE_ARCH" olddefconfig
     fi
 
-    echo "${WHITE}"
-    echo "Running menuconfig..."
-    echo "${NORMAL}"
-    if [[ -n "$CROSS_COMPILE_PREFIX" ]]; then
-        # Cross-compile
-        if [[ -n "$KERNEL_BUILD_DIR" ]]; then
-            # Separate build dir.
-            make ARCH="$MAKE_ARCH" CROSS_COMPILE="${CROSS_COMPILE_PREFIX}" O="$KERNEL_BUILD_DIR" menuconfig
+    # Run menuconfig so user can customize the kernel config.
+    echo ""
+    echo "${WHITE}Do you want to run menuconfig? (y/n)${NORMAL}"
+    read -r answer
+    if [[ "$answer" =~ ^[Yy]$ ]]; then
+        if [[ -n "$CROSS_COMPILE_PREFIX" ]]; then
+            # Cross-compile
+            if [[ -n "$KERNEL_BUILD_DIR" ]]; then
+                # Separate build dir.
+                make ARCH="$MAKE_ARCH" CROSS_COMPILE="${CROSS_COMPILE_PREFIX}" O="$KERNEL_BUILD_DIR" menuconfig
+            else
+                make ARCH="$MAKE_ARCH" CROSS_COMPILE="${CROSS_COMPILE_PREFIX}" menuconfig
+            fi
         else
-            make ARCH="$MAKE_ARCH" CROSS_COMPILE="${CROSS_COMPILE_PREFIX}" menuconfig
+            # Native build
+            if [[ -n "$KERNEL_BUILD_DIR" ]]; then
+                # Separate build dir.
+                make ARCH="$MAKE_ARCH" O="$KERNEL_BUILD_DIR" menuconfig
+            else
+                make ARCH="$MAKE_ARCH" menuconfig
+            fi
         fi
     else
-        # Native build
-        if [[ -n "$KERNEL_BUILD_DIR" ]]; then
-            # Separate build dir.
-            make ARCH="$MAKE_ARCH" O="$KERNEL_BUILD_DIR" menuconfig
-        else
-            make ARCH="$MAKE_ARCH" menuconfig
-        fi
+        echo "${WHITE}Skipping menuconfig.${NORMAL}"
     fi
 fi
 
 # If this is an Orin Nano, set for performance mode.
-if [[ $(cat /sys/firmware/devicetree/base/model) == *"Orin Nano"* ]]; then
-    echo "${WHITE}"
-    echo "This is Orin Nano - setting for performance mode."
+if grep -q "Orin Nano" /sys/firmware/devicetree/base/model; then
+    echo "${WHITE}This is Orin Nano - setting for performance mode."
     echo "${NORMAL}"
     sudo cpupower frequency-set -g performance
 fi
@@ -319,7 +314,7 @@ echo "// KERNEL_BUILD_DIR = ${KERNEL_BUILD_DIR}" >> ${LOG_FILE}
 echo "// ${GCC_VERSION}" >> ${LOG_FILE}
 
 if $CONFIGURE; then
-echo "// CS9 kernel config file: ${CONFIG_FILE}"
+echo "// CS9 kernel config file: ${CONFIG_FILE}" >> ${LOG_FILE}
 fi
 echo "//---------------------------------------------------------------" >> ${LOG_FILE}
 echo "" >> ${LOG_FILE}
@@ -329,8 +324,8 @@ START_TIME=$(date +%s)
 cd "$KERNEL_SRC_DIR" || exit 1
 
 # Build the CS9 kernel.
-echo "${WHITE}"
-echo "Building the CS9 kernel..."
+echo ""
+echo "${WHITE}Building the CS9 kernel..."
 echo "${NORMAL}"
 if [[ -n "$CROSS_COMPILE_PREFIX" ]]; then
     # Cross compile.
@@ -404,8 +399,7 @@ else
     fi
 fi
 
-echo "${WHITE}"
-echo "Build time: ${BUILD_MINUTES} min, ${BUILD_SECONDS} sec"
+echo "${WHITE}Build time: ${BUILD_MINUTES} min, ${BUILD_SECONDS} sec"
 echo "${NORMAL}"
 echo "// Build time: ${BUILD_MINUTES} min, ${BUILD_SECONDS} sec" >> "$LOG_FILE"
 
